version: 0.0

os: linux

files:
  - source: /path/to/yourfile.html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/configure_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_httpd.sh
      timeout: 300
      runas: root
